In [7]:
# 引入 MySQLdb 模組，提供連接 MySQL 的功能
import pymysql

# 連接 MySQL 資料庫
db = pymysql.connect(host="10.2.1.234", user="root", password="tibame", db="Movies")
cursor = db.cursor()

#輸入movieId
in_ = 100
# 執行 MySQL 查詢指令
cursor.execute("SELECT genres FROM movie WHERE  movieId = {} ".format(in_))
# 取回所有查詢結果
results = cursor.fetchall()
#for i in results:
 #   print(i)
# 輸出結果
for record in results:
  col1 = record[0]
  #col2 = record[1]
  #col3 = record[2]
  #print( "%s, %s" % (col1, col3))
  col1 = col1.split("|")
  print((col1)[0])
# 關閉連線
db.close()

Drama

In [10]:
# 引入 MySQLdb 模組，提供連接 MySQL 的功能
import pymysql
import re
# 連接 MySQL 資料庫
db = pymysql.connect(host="10.2.1.234",
    user="root", passwd="tibame", db="Movies")
cursor = db.cursor()


mi = [138580, 241, 4303, 1, 140990]
a = []
b = []
for i in range(0, 5):
    #print(mi[i])
#輸入movieId
    in_ = mi[i]
    cursor.execute("SELECT * FROM movie WHERE  movieId = {} ".format(in_))
# 執行 MySQL 查詢指令
    #cursor.execute("SELECT genres FROM movie WHERE  movieId = {} ".format(in_))
# 取回所有查詢結果
    results = cursor.fetchall()
#for i in results:
 #   print(i)
# 輸出結果

    
    for record in results:
        #col1 = record[0]
        #col2 = record[1]
        col3 = record[2]
        #print( "%s, %s, %s" % (col1,col2, col3))
        col3 = col3.split("|")
        #print((col3)[0])
        type_ = col3[0]
        type_ = type_.split('"')[0]
        a.append(type_)
        
print(a)
print("====================================")
# 關閉連線
db.close()


for item in a:
    category = ['Horror','Children','Comedy','Adventure']
    for i in category:
        pattern =  r'.*{}.*'.format(i)
        result = re.match(pattern,item)
        if result != None:
            #print(i)
            b.append(i)
        else:
            pass
print(b)
print("====================================")

['Horror', 'Children', 'Comedy\r', 'Adventure', ' La (1937)']
====================================
['Horror', 'Children', 'Comedy', 'Adventure']
====================================

In [17]:
# 引入 MySQLdb 模組，提供連接 MySQL 的功能
import pymysql
import re
#新者用者推薦
db = pymysql.connect(host="10.2.1.234", user="root", passwd="tibame", db="TVShows")
cursor = db.cursor()
 #   cursor.execute("SELECT * FROM movie WHERE  movieId = {} ".format(in_))
cursor.execute("SELECT Title, Year_x, imdbRating, Genre FROM imdbdata order by imdbRating DESC, Year_x DESC ")
result = cursor.fetchall()

for i in range(5):
    top5 = result[i]
    top5_ = result[i][3].split("|")
    #print(top5)
    print(top5[0], top5_)

L'Italia a Morsi ['Documentary']
Daba Teziane ['Comedy', ' Drama', ' Family', ' Romance']
À Brasileira ['Documentary']
Boss Hoggin Road Trip Series ['Reality-TV']
Shiny New Things ['Drama']

In [29]:
# 引入 MySQLdb 模組，提供連接 MySQL 的功能
import pymysql
import re
# 連接 MySQL 資料庫
db = pymysql.connect(host="10.2.1.234",
    user="root", passwd="tibame", db="Movies")
cursor = db.cursor()





# inputId = request.form
# results = df[df['userId'] == inputId]['movieId']
# mi = result[0]
#movieid輸入
mi = [138580, 241, 4303, 1, 140990]
a = []
b = []
user1 = []
for i in range(0, 5):
    #print(mi[i])
#輸入movieId
    in_ = mi[i]
    cursor.execute("SELECT * FROM movie WHERE  movieId = {} ".format(in_))
# 執行 MySQL 查詢指令
    #cursor.execute("SELECT genres FROM movie WHERE  movieId = {} ".format(in_))
# 取回所有查詢結果
    results = cursor.fetchall()
#for i in results:
 #   print(i)
# 輸出結果

    
    for record in results:
        #col1 = record[0]
        #col2 = record[1]
        col3 = record[2]
        #print( "%s, %s, %s" % (col1,col2, col3))
        col3 = col3.split("|")
        #print((col3)[0])
        type_ = col3[0]
        type_ = type_.split('"')[0]
        a.append(type_)
        
print(a)
print("====================================")
# 關閉連線
db.close()



for item in a:
    category = ['Horror','Children','Comedy','Adventure']
    for i in category:
        pattern =  r'.*{}.*'.format(i)
        result = re.match(pattern,item)
        if result != None:
            #print(i)
            b.append(i)
        else:
            pass
print("custype:",b)
print("=====================")


db = pymysql.connect(host="10.2.1.234", user="root", passwd="tibame", db="TVShows")
cursor = db.cursor()


 #   cursor.execute("SELECT * FROM movie WHERE  movieId = {} ".format(in_))
cursor.execute("SELECT Title, Year_x, imdbRating, Genre FROM imdbdata order by imdbRating DESC, Year_x DESC ")
result = cursor.fetchall()

count = 0
for record in result:
    col1 = record[0]
    col2 = record[1]
    col3 = record[2]
    col4 = record[3]
    col4 = col4.split("|")

    for genre in col4:
        if count >  4:
            break
        for custype in b:
            if genre == custype:
                output = col1
                print(output)
                #print("%s, %s, %s, %s" % (col1,col2, col3, col4))
                count += 1
            else:
                pass

['Horror', 'Children', 'Comedy\r', 'Adventure', ' La (1937)']
====================================
custype: ['Horror', 'Children', 'Comedy', 'Adventure']
=====================
Daba Teziane
El Harba
Thuththiri
Egotastic FunTime!
Ring Rajen

In [ ]:
from flask import Flask, render_template, request
import pyarrow as pa
import redis
import pandas as pd
app = Flask(__name__)

import pymysql
import re


r = redis.Redis(host='10.2.1.234', port=6379, db=0)
context = pa.default_serialization_context()

# 從 redis 讀取 recomm 資料
data = r.get('recomm')

# 反序列化
df = pd.DataFrame.from_dict(context.deserialize(data))




@app.route('/',methods=['Get'])
def index():
   return render_template('index.html')

@app.route('/hello',methods=['Get'])
def hello_world():
   return 'hello world'

@app.route('/result',methods = ['POST', 'GET'])
def result():
    if request.method == 'POST':

    
    #連接movie資料庫
        movie = pd.read_csv('movies.csv')

    #接收movieId
        input_ = request.form.to_dict()
        movie_ID = input_['電影名字']
        input_s = int(movie_ID)

    #movieId帶進模型運算
        m  = movie.iloc[input_s]
        select = pd.Series(m, index = m.keys())

    #取出結果
        #a = 選取user的電影類型
        a = select[2]
        #c =split結果變list
        c = a.split("|")
        
        b = []
        user1 = [] 
        for item in c:
            category = ['Horror','Children','Comedy','Adventure', 'Fantasy', 'Animation', 'Musical','Action', 'Crime', 'Thriller','Romance', 'Documentary', 'War', 'Drama', 'Mystery']
            for i in category:
                pattern =  r'.*{}.*'.format(i)
                result = re.match(pattern,item)
                if result != None:
                    b.append(i)
                else:
                    pass
    
        db = pymysql.connect(host="10.2.1.234", user="root", passwd="tibame", db="TVShows")
        cursor = db.cursor()
        cursor.execute("SELECT Title, Year_x, imdbRating, Genre FROM imdbdata order by imdbRating DESC, Year_x DESC ")
        result = cursor.fetchall()
        count = 0
        ans = []
        for record in result:
            col1 = record[0]
            col2 = record[1]
            col3 = record[2]
            col4 = record[3]
            col4 = col4.split("|")

            for genre in col4:
                if count >  4:
                    break
                for custype in b:
                    if genre == custype:
                        ans.append(col1)
                        count += 1
                    else:
                        pass
    
    output = {
    "1":ans[0],
    "2":ans[1],
    "3":ans[2],
    "4":ans[3],
    "5":ans[4]
}

    return render_template("result.html",result = output)


if __name__ == "__main__":
    app.run(debug=True, host='localhost', port=5000)

In [ ]:
import pyarrow as pa
import redis
import pandas as pd

# 宣告 redis 連線
r = redis.Redis(host='10.2.1.234', port=6379, db=0)
context = pa.default_serialization_context()

# 從 redis 讀取 recomm 資料
data = r.get('recomm')

# 反序列化
df = pd.DataFrame.from_dict(context.deserialize(data))

print(type(df))

print(df.head())

In [ ]:
import re
import pymysql
movie = pd.read_csv('movies.csv')
moId = 2
a=movie[movie['movieId'] == moId]['genres'].apply(lambda x:  x.split('|')[0]).to_string()
print(a)